# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release CD

on:
  push:
    branches: [ main ]

jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    #THIS WORKS
    # - name: Publish
    #   run: |
    #     npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    #     npm ci
    #     npm publish
    #   env:
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Test
      run: npm test
    - name: Release new version to NPM
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release