# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Tests

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          [
            3.x,
            4.x,
            5.x,
            6.x,
            7.x,
            8.x,
            9.x,
            10.x,
            11.x
          ]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clean Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
