# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and Release CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Full versions omitted for publish testing
        # node-version: [12.x, 14.x, 16.x, 17.x]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present
    - run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    # - run: npx semantic-release
    #   env:
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Gnerate Release
      run:
        gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
        gh release list
    - name: Publish
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm ci
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}